export const SUBSCRIBE_NOT_FOUND_ERROR = 'Subscribe not found';
export const GET_FOLLOWERS_ERROR_TYPE = 'GET_VIDEOS_ERROR';

export const DELETE_SUBSCRIBE_ERROR_TYPE = 'DELETE_SUBSCRIBE_ERROR';

export const CREATE_SUBSCRIBE_ERROR_TYPE = 'CREATE_SUBSCRIBE_ERROR';
